#!/bin/sh

# Build the patches pack and upload to Tetxurejam.
# Assumes this project's directory is a sibling to the texturejam one.

cd $(dirname $0)/..

ver=$(cat VERSION)
dir=../texturejam/static/texturepacks

maketexture --force -v --out=$dir/patches.$ver.zip patches.tprx

cd $dir
git add patches.$ver.zip
git commit -m 'Update patches texture pack'
git push


