#!/bin/sh

# Build the patches pack and upload to Tetxurejam.
# Assumes this project's directory is a sibling to the texturejam one.

cd $(dirname $0)/..

cp -p ../texturepacker/minecraft/maps/* rx/maps
scripts/mkpatchesr